fullnameOverride: "kube-prometheus-stack"
grafana:
  sidecar:
    dashboards:
      searchNamespace: "ALL"
prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - monitoring
            - kafka
            - strimzi
    podMonitorNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - monitoring
            - kafka
            - strimzi
    serviceMonitorSelector:
      matchExpressions:
        - { key: release, operator: In, values: [ kube-prometheus-stack, strimzi-kafka ] }
    podMonitorSelector:
      matchExpressions:
        - { key: release, operator: In, values: [ kube-prometheus-stack, strimzi-kafka ] }
kube-state-metrics:
  # Comma-separated list of additional Kubernetes label keys that will be used in the resource's
  # labels metric. By default the metric contains only name and namespace labels.
  # To include additional labels, provide a list of resource names in their plural form and Kubernetes
  # label keys you would like to allow for them (Example: '=namespaces=[k8s-label-1,k8s-label-n,...],pods=[app],...)'.
  # A single '*' can be provided per resource instead to allow any labels, but that has
  # severe performance implications (Example: '=pods=[*]').
  metricLabelsAllowlist:
    - "pods=[pipeline]"
