apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rest-service.fullname" . }}
  labels:
    {{- include "rest-service.labels" . | nindent 4 }}
data:
  config.properties: |
  {{- if .Values.app.config }}
  {{- .Values.app.config | nindent 4 }}
  {{- end }}
