apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rest-service.fullname" . }}
  labels:
    {{- include "rest-service.labels" . | nindent 4 }}
stringData:
  secret.properties: |
  {{- if .Values.app.secret }}
  {{- .Values.app.secret | nindent 4 }}
  {{- end }}
