apiVersion: v1
kind: Service
metadata:
  name: {{ include "rest-service.fullname" . }}
  labels:
    {{- include "rest-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "rest-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  type: {{ .Values.service.type }}
