{
 "title": "KPOps pipeline Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Pipeline", "query": { "query": "kube_pod_labels" } },
   { "name": "ErrorSuffix", "query": "error" }
  ]
 },
 "panels": [
  { "title": "$Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Pipeline" },
  {
   "title": "$Pipeline pipeline - messages in per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_topic_partition_current_offset{topic=~\"$Pipeline-.*\"}[5m])) unless sum by(topic) (rate(kafka_topic_partition_current_offset{topic=~\"$Pipeline-.*-$ErrorSuffix\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Pipeline pipeline - dead letters per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_topic_partition_current_offset{topic=~\"$Pipeline.*-$ErrorSuffix\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Pipeline pipeline - lag of consumers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(consumergroup) (kafka_consumergroup_lag_sum{topic=~\"$Pipeline-.*\", consumergroup=~\".+\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}