environment: development

topic_name_config:
  default_error_topic_name: "${component_name}-error-topic"
  default_output_topic_name: "${component_name}-topic"

broker: "cluster-kafka-bootstrap.kafka:9092"

schema_registry_url: "http://k8kafka-cp-schema-registry.kafka:8081"

kafka_rest_host: "http://localhost:8082"

kafka_connect_host: "http://localhost:8083"

defaults_path: defaults
